# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingsUIui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsWindow(object):
    def setupUi(self, SettingsWindow):
        SettingsWindow.setObjectName("SettingsWindow")
        SettingsWindow.resize(649, 540)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SettingsWindow.sizePolicy().hasHeightForWidth())
        SettingsWindow.setSizePolicy(sizePolicy)
        SettingsWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        SettingsWindow.setAcceptDrops(False)
        SettingsWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        SettingsWindow.setAutoFillBackground(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(SettingsWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_layout = QtWidgets.QGridLayout()
        self.main_layout.setHorizontalSpacing(1)
        self.main_layout.setObjectName("main_layout")
        self.pos_settings_layout = QtWidgets.QGridLayout()
        self.pos_settings_layout.setObjectName("pos_settings_layout")
        self.azimuth_rbttn = QtWidgets.QRadioButton(SettingsWindow)
        self.azimuth_rbttn.setObjectName("azimuth_rbttn")
        self.pos_settings_layout.addWidget(self.azimuth_rbttn, 4, 1, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(SettingsWindow)
        self.spinBox.setObjectName("spinBox")
        self.pos_settings_layout.addWidget(self.spinBox, 3, 1, 1, 1)
        self.increment_suffix_label = QtWidgets.QLabel(SettingsWindow)
        self.increment_suffix_label.setObjectName("increment_suffix_label")
        self.pos_settings_layout.addWidget(self.increment_suffix_label, 3, 2, 1, 1)
        self.elevation_rbttn = QtWidgets.QRadioButton(SettingsWindow)
        self.elevation_rbttn.setObjectName("elevation_rbttn")
        self.pos_settings_layout.addWidget(self.elevation_rbttn, 5, 1, 1, 1)
        self.sweep_type_cBox = QtWidgets.QComboBox(SettingsWindow)
        self.sweep_type_cBox.setObjectName("sweep_type_cBox")
        self.pos_settings_layout.addWidget(self.sweep_type_cBox, 2, 1, 1, 1)
        self.sweep_type_label = QtWidgets.QLabel(SettingsWindow)
        self.sweep_type_label.setObjectName("sweep_type_label")
        self.pos_settings_layout.addWidget(self.sweep_type_label, 2, 0, 1, 1)
        self.increment_label = QtWidgets.QLabel(SettingsWindow)
        self.increment_label.setObjectName("increment_label")
        self.pos_settings_layout.addWidget(self.increment_label, 3, 0, 1, 1)
        self.main_layout.addLayout(self.pos_settings_layout, 3, 1, 1, 1)
        self.pos_settings_label = QtWidgets.QLabel(SettingsWindow)
        self.pos_settings_label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.pos_settings_label.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.pos_settings_label.setObjectName("pos_settings_label")
        self.main_layout.addWidget(self.pos_settings_label, 2, 0, 1, 1)
        self.meas_type_label = QtWidgets.QLabel(SettingsWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meas_type_label.sizePolicy().hasHeightForWidth())
        self.meas_type_label.setSizePolicy(sizePolicy)
        self.meas_type_label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.meas_type_label.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.meas_type_label.setObjectName("meas_type_label")
        self.main_layout.addWidget(self.meas_type_label, 0, 0, 1, 1)
        self.vna_settings_tabs = QtWidgets.QTabWidget(SettingsWindow)
        self.vna_settings_tabs.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vna_settings_tabs.sizePolicy().hasHeightForWidth())
        self.vna_settings_tabs.setSizePolicy(sizePolicy)
        self.vna_settings_tabs.setMaximumSize(QtCore.QSize(16777215, 300))
        self.vna_settings_tabs.setTabPosition(QtWidgets.QTabWidget.North)
        self.vna_settings_tabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.vna_settings_tabs.setUsesScrollButtons(False)
        self.vna_settings_tabs.setMovable(False)
        self.vna_settings_tabs.setObjectName("vna_settings_tabs")
        self.list_tab = QtWidgets.QWidget()
        self.list_tab.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_tab.sizePolicy().hasHeightForWidth())
        self.list_tab.setSizePolicy(sizePolicy)
        self.list_tab.setObjectName("list_tab")
        #
        self.list_tab_layout = QtWidgets.QGridLayout(self.list_tab)
        self.list_tab_layout.setObjectName("list_tab_layout")
        self.freq_list_label = QtWidgets.QLabel(self.list_tab)
        self.freq_list_label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.freq_list_label.sizePolicy().hasHeightForWidth())
        self.freq_list_label.setSizePolicy(sizePolicy)
        self.freq_list_label.setObjectName("freq_list_label")
        self.list_tab_layout.addWidget(self.freq_list_label, 0, 0, 1, 1)
        self.freq_list_lineEdit = QtWidgets.QLineEdit(self.list_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.freq_list_lineEdit.sizePolicy().hasHeightForWidth())
        self.freq_list_lineEdit.setSizePolicy(sizePolicy)
        self.freq_list_lineEdit.setObjectName("freq_list_lineEdit")
        self.list_tab_layout.addWidget(self.freq_list_lineEdit, 0, 1, 1, 1)
        self.vna_settings_tabs.addTab(self.list_tab, "")
        self.sweep_tab = QtWidgets.QWidget()
        self.sweep_tab.setObjectName("sweep_tab")
        # Sweep tab Layout
        self.sweep_tab_layout = QtWidgets.QGridLayout(self.sweep_tab)
        self.sweep_tab_layout.setObjectName("sweep_tab_layout")
        self.start_label = QtWidgets.QLabel(self.sweep_tab)
        self.start_label.setObjectName("start_label")
        self.sweep_tab_layout.addWidget(self.start_label, 0, 0, 1, 1)
        self.start_freq_lineEdit = QtWidgets.QLineEdit(self.sweep_tab)
        self.start_freq_lineEdit.setObjectName("start_freq_lineEdit")
        self.sweep_tab_layout.addWidget(self.start_freq_lineEdit, 0, 1, 1, 1)
        self.start_label_suffix = QtWidgets.QLabel(self.sweep_tab)
        self.start_label_suffix.setObjectName("start_label_suffix")
        self.sweep_tab_layout.addWidget(self.start_label_suffix, 0, 2, 1, 1)
        self.end_label = QtWidgets.QLabel(self.sweep_tab)
        self.end_label.setObjectName("end_label")
        self.sweep_tab_layout.addWidget(self.end_label, 1, 0, 1, 1)
        self.end_freq_lineEdit = QtWidgets.QLineEdit(self.sweep_tab)
        self.end_freq_lineEdit.setObjectName("end_freq_lineEdit")
        self.sweep_tab_layout.addWidget(self.end_freq_lineEdit, 1, 1, 1, 1)
        self.end_label_suffix = QtWidgets.QLabel(self.sweep_tab)
        self.end_label_suffix.setObjectName("end_label_suffix")
        self.sweep_tab_layout.addWidget(self.end_label_suffix, 1, 2, 1, 1)
        self.num_pts_label = QtWidgets.QLabel(self.sweep_tab)
        self.num_pts_label.setObjectName("num_pts_label")
        self.sweep_tab_layout.addWidget(self.num_pts_label, 2, 0, 1, 1)
        self.num_points_lineEdit = QtWidgets.QLineEdit(self.sweep_tab)
        self.num_points_lineEdit.setObjectName("num_points_lineEdit")
        self.sweep_tab_layout.addWidget(self.num_points_lineEdit, 2, 1, 1, 1)
        self.vna_settings_tabs.addTab(self.sweep_tab, "")
        self.main_layout.addWidget(self.vna_settings_tabs, 1, 0, 1, 2)
        self.calibration_cbox = QtWidgets.QCheckBox(SettingsWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibration_cbox.sizePolicy().hasHeightForWidth())
        self.calibration_cbox.setSizePolicy(sizePolicy)
        self.calibration_cbox.setAcceptDrops(False)
        self.calibration_cbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.calibration_cbox.setObjectName("calibration_cbox")
        self.main_layout.addWidget(self.calibration_cbox, 4, 1, 1, 1)
        self.select_pbttn = QtWidgets.QPushButton(SettingsWindow)
        self.select_pbttn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.select_pbttn.setToolTip("")
        self.select_pbttn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.select_pbttn.setObjectName("select_pbttn")

        # self.select_pbttn.clicked.connect(self.switch)

        self.main_layout.addWidget(self.select_pbttn, 5, 1, 1, 1)
        self.cancel_pbttn = QtWidgets.QPushButton(SettingsWindow)
        self.cancel_pbttn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancel_pbttn.sizePolicy().hasHeightForWidth())
        self.cancel_pbttn.setSizePolicy(sizePolicy)
        self.cancel_pbttn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cancel_pbttn.setObjectName("cancel_pbttn")
        self.main_layout.addWidget(self.cancel_pbttn, 5, 0, 1, 1)
        self.verticalLayout.addLayout(self.main_layout)

        self.retranslateUi(SettingsWindow)
        self.vna_settings_tabs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(SettingsWindow)

    def retranslateUi(self, SettingsWindow):
        _translate = QtCore.QCoreApplication.translate
        SettingsWindow.setWindowTitle(_translate("SettingsWindow", "Settings Window"))
        self.azimuth_rbttn.setText(_translate("SettingsWindow", "Azimuth"))
        self.increment_suffix_label.setText(_translate("SettingsWindow", "degrees"))
        self.elevation_rbttn.setText(_translate("SettingsWindow", "Elevation"))
        self.sweep_type_label.setText(_translate("SettingsWindow", "Sweep Type:"))
        self.increment_label.setText(_translate("SettingsWindow", "Increment:"))
        self.pos_settings_label.setText(_translate("SettingsWindow", "Positioner Settings"))
        self.meas_type_label.setText(_translate("SettingsWindow", "Measurement Type"))
        self.freq_list_label.setText(_translate("SettingsWindow", "Enter List of Frequencies:"))
        self.vna_settings_tabs.setTabText(self.vna_settings_tabs.indexOf(self.list_tab),
                                          _translate("SettingsWindow", "List"))
        self.start_label.setText(_translate("SettingsWindow", "Start:"))
        self.start_label_suffix.setText(_translate("SettingsWindow", "Hz"))
        self.end_label.setText(_translate("SettingsWindow", "End:"))
        self.end_label_suffix.setText(_translate("SettingsWindow", "Hz"))
        self.num_pts_label.setText(_translate("SettingsWindow", "Number of Points:"))
        self.vna_settings_tabs.setTabText(self.vna_settings_tabs.indexOf(self.sweep_tab),
                                          _translate("SettingsWindow", "Sweep"))
        self.calibration_cbox.setText(_translate("SettingsWindow", "Calibration"))
        self.select_pbttn.setText(_translate("SettingsWindow", "Select"))
        self.cancel_pbttn.setText(_translate("SettingsWindow", "Cancel"))

